#!/bin/bash
export XSGMB=../../../../john/xsgmb/xsgmb
export MAKEBG=../../../../util/makebg
export GBSWD=../../../../util/gbswd
export MAKEPKG=../../../../john/makepkg/makepkg
export GMBFNT=../../../../john/gmbfnt/gmbfnt
export MAKETEXT=../../../../john/maketext/maketext
export MAPDELTA=../../../../util/mapdelta
export RIDECNV2=../../../../util/ridecnv2
export PINMAP=../../util/pinmap
export CONV=../../util/conv
