#!/bin/bash
set -e
. ../tools

rm -f *.hi *.lo *.map *.chr *.pkg *.equ swd/* *.rgb
for f in *.pcx; do
 $XSGMB @cbitmap.cmd $f
done

for f in *.map; do
 $MAKEPKG -offset 8 -split $f
done

$GBSWD -d *.chr *.hi

for f in *.pcx; do
 t=${f%.*}
 $MAKEPKG -OutputFormat BIN -OutputHeader YES -OutputOrder LOHI swd/$t.chr swd/$t.hi $t.rgb
done

cp swd/*.pkg .
