#!/bin/bash
rm -f filesys.asm filesys.b?? sprites.b??
cat freeintl.lst john/fileintl.lst dave/filedave.lst dave/fileintl.lst > filesys.lst
../../../util/gather filesys.lst 14:4000
cat dave/sprdave.lst john/sprintl.lst > sprites.lst
../../../util/gmbspr2 -a0A:4280 sprites @sprites.lst
../../../util/animrgb/animrgb sprites.lst
