#!/bin/bash
set -e
rm -f swd/* *.hi *.lo *.map *.chr *.pkg *.equ *.rgb
. ../../tools

#for f in b*.bbm; do
# $XSGMB @bbitmap.cmd $f
#done

#for f in c*.bbm; do
# $XSGMB @cbitmap.cmd $f
#done

for f in b*.pcx; do
 $XSGMB @bbitmap.cmd $f
done

for f in c*.pcx; do
 $XSGMB @cbitmap.cmd $f
done

for f in c*.map; do
 $MAKEPKG -offset 8 -split $f
done

$GBSWD -g -d -n  *.chr
$GBSWD -g -d -n  *.hi

#for f in b*.bbm; do
# t=${f%.*}
# $MAKEPKG -OutputFormat BIN -OutputHeader YES -OutputOrder LOHI swd/$t.chr
#done
#for f in c*.bbm; do
# t=${f%.*}
# $MAKEPKG -OutputFormat BIN -OutputHeader YES -OutputOrder LOHI swd/$t.chr swd/$t.hi $t.rgb
#done

for f in b*.pcx; do
 t=${f%.*}
 $MAKEPKG -OutputFormat BIN -OutputHeader YES -OutputOrder LOHI swd/$t.chr
done
for f in c*.pcx; do
 t=${f%.*}
 $MAKEPKG -OutputFormat BIN -OutputHeader YES -OutputOrder LOHI swd/$t.chr swd/$t.hi $t.rgb
done

mv swd/*.pkg .

#for f in b*.abm; do  # b*.spr
# $XSGMB @bspr.cmd $f
#done

for f in c*.abm; do  # c*.spr
 $XSGMB @cspr.cmd $f
done
