#!/bin/tcsh
rm *.map *.chr *.rgb *.equ *.dm? swd/* *.trg *.ch0 *.ch1 *.ch2 *.ch3 *.ch4 *.pkg

crossfade

#foreach zzz (*.pcx)
#xsgmb @bg.cmd $zzz
#end

#foreach zzz (*.map)
#makebg $zzz
#end

foreach zzz (*.spr)
xsgmb @cut.cmd $zzz
end

bumperpackages

#foreach zzz (*.prj)
#tumerd $zzz
#end

xsgmb @bgnomap.cmd digits.pcx

./resmaps


gbswd -d *.dm? *.chr *.bg *.pmp *.map
